<!DOCTYPE html>
<html>
    <head>
        <title>DataWarehouse : CDWH outages</title>
        <link rel="stylesheet" href="styles/site.css" type="text/css" />
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>

    <body class="theme-default aui-theme-default">
        <div id="page">
            <div id="main" class="aui-page-panel">
                <div id="main-header">
                    <div id="breadcrumb-section">
                        <ol id="breadcrumbs">
                            <li class="first">
                                <span><a href="index.html">DataWarehouse</a></span>
                            </li>
                                                    <li>
                                <span><a href="DataWarehouse_33423377.html">DataWarehouse</a></span>
                            </li>
                                                    <li>
                                <span><a href="Wiki_33424094.html">Wiki</a></span>
                            </li>
                                                    <li>
                                <span><a href="Problem-logs_33423661.html">Problem logs</a></span>
                            </li>
                                                </ol>
                    </div>
                    <h1 id="title-heading" class="pagetitle">
                                                <span id="title-text">
                            DataWarehouse : CDWH outages
                        </span>
                    </h1>
                </div>

                <div id="content" class="view">
                    <div class="page-metadata">
                        
        
    
        
    
        
        
            Created by <span class='author'> Michael Hadorn</span>, last modified by <span class='editor'> Richard Marti</span> on Aug. 29, 2023
                        </div>
                    <div id="main-content" class="wiki-content group">
                    <div class="confluence-information-macro confluence-information-macro-information"><span class="aui-icon aui-icon-small aui-iconfont-info confluence-information-macro-icon"></span><div class="confluence-information-macro-body"><p>Diese Seite listet alle CDWH Ausfälle auf, um alle Probleme aufzulisten. Bitte den neusten Eintrag zuoberst eintragen.</p></div></div><h1 id="CDWHoutages-Template">Template</h1><h2 id="CDWHoutages-[date]:[shortproblem]">[date]: [short problem]</h2><p>[Problem]</p><hr/><h1 id="CDWHoutages-Ausfälle">Ausfälle</h1><h2 id="CDWHoutages-29.08.2023:COPRA">29.08.2023: COPRA</h2><p>Restore-Datenbank war nicht verfügbar.</p><h2 id="CDWHoutages-25.-28.08.2023:RIS">25.-28.08.2023: RIS</h2><p>Der Job am 24.08.2023 war nicht sauber beendet, worauf der RIS-Job vier Tage lang nicht gestartet ist.</p><h2 id="CDWHoutages-24.08.2023:MemoryIssues:Cato,Copra,Zamd,Mosaiq,Sema">24.08.2023: Memory Issues: Cato, Copra, Zamd, Mosaiq, Sema</h2><p>Memory-Issues auf dem DS-Server. Copra, Zamd, Mosaiq, Sema sind gar nicht gestartet</p><h2 id="CDWHoutages-02.08.2023:SERVMAN,MEONA,CATO,ISOP">02.08.2023: SERVMAN, MEONA, CATO, ISOP</h2><p>Memory-Issues auf dem DS-Server</p><h2 id="CDWHoutages-20.06.2023:2xSERVMAN">20.06.2023: 2 x SERVMAN</h2><p>02:00:35 The SELECT permission was denied on the object 'tblRuns', database 'dbcareV6_Reporting', schema 'iexp'<br/>07:00:26 The SELECT permission was denied on the object 'tblRuns', database 'dbcareV6_Reporting', schema 'iexp'</p><p><span style="font-size: 1.43em;letter-spacing: -0.008em;">13.06.2023: SERVMAN</span></p><pre>07:10:06: ODBC data source &lt;CLSQL1219\IBP2&gt; error message for operation &lt;SQLFetchScroll&gt;: &lt;[Microsoft][ODBC SQL Server Driver][SQL Server]</pre><pre>Transaction (Process ID 131) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.&gt;</pre><h2 id="CDWHoutages-09.06.2023:FCT_OPERATION_PART">09.06.2023: FCT_OPERATION_PART</h2><p>Unique Constraint Violation wegen einer doppelten OP-Code-Erfassung für eine OP.</p><h2 id="CDWHoutages-26.05.2023:METAVISION,COPRA,CATO,MOSAIQ,MEONA">26.05.2023: METAVISION, COPRA, CATO, MOSAIQ, MEONA</h2><div class="log-datetime utilGrayMid--text">There was an error in the VM-Backup process, therefore the MSSQL-bakcupserver was unavailable during the night.<br/><h2 id="CDWHoutages-25.05.2023:Sentrysuite">25.05.2023: Sentrysuite</h2><div class="log-datetime utilGrayMid--text">02:52:39: Your system is running low on virtual memory. Total size is &lt;71679&gt;, available &lt;3409&gt;.<pre> (14.2) 05-25-23 02:52:39 (E) (18800:16436) RUN-050316: |Session BJ_LZ_CATO|Work flow WF_LZ_CAT|Function CF_MD_WF_CONTROL|Function CF_RAISE_ERROR
 &gt;&gt;&gt;&gt;&gt; INFO [BJ_LZ_CATO -&gt; CF_MD_WF_CONTROL] - There was an error in the workflow 'WF_LZ_CAT'<br/><br/></pre></div><div class="log-datetime utilGrayMid--text"><span style="font-size: 1.43em;">18.05.2023-22.05.2023: Openspecimen</span></div></div><div class="log-datetime utilGrayMid--text"><div class="log-datetime utilGrayMid--text">TNS-File was outdated several days, due to Oracle Database Migration. No impact on CDWH, we do not use Openspecimena data yet.<br/><br/></div><div class="log-datetime utilGrayMid--text"><h2 id="CDWHoutages-29.04.2023:Sentrysuite">29.04.2023: Sentrysuite</h2><div class="log-datetime utilGrayMid--text">01:03:25: [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied<br/><br/></div></div></div><div class="log-datetime utilGrayMid--text"><div class="log-datetime utilGrayMid--text"><h2 id="CDWHoutages-28.04.2023:ISOP">28.04.2023: ISOP</h2><div class="log-datetime utilGrayMid--text">03:26:14: [SAP AG][LIBODBCHDB DLL][HDBODBC] Integrity constraint violation;301 unique constraint violated<br/>→ Schedule von RT-Job und Full-Load haben sich überschnitten → korrigiert<br/><span><br/></span></div><div class="log-datetime utilGrayMid--text"><h2 class="log-datetime utilGrayMid--text" id="CDWHoutages-27.04.2023-04.05.2023:FCT_OXYGEN_THERAPY_METAVISION"><span>27.04.2023 - 04.05.2023: FCT_OXYGEN_THERAPY_METAVISION</span></h2><p>301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_FCT_OXYGEN_THERAPY_METAVISION&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 393): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_FCT_OXYGEN_THERAPY_METAVISION&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 596):<br/>Table(TZ_FCT_OXYGEN_THERAPY_METAVISION), Index(_SYS_TREE_CS_#8910713_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_FCT_OXYGEN_THERAPY_METAVISIONen,<br/>column=\'OTMT_BK\', value=\'4d45547c38313837347c3230323330343237313630303030\', pos=331021; indexname=_SYS_TREE_CS_#8910713_#0_#P0'</p><p><br/></p></div></div><span style="font-size: 1.43em;">24.04.2023: CDWH</span></div><div class="log-datetime utilGrayMid--text">04:41:02: transformation_qscorecard.qsw_downfall und transformation_qscorecard.qsw_catheter_urinary</div><p>hdbcli.dbapi.Error: (-10709, 'Connect failed (connect timeout expired) (172.18.0.8:49664 -&gt; <a href="http://ictthdbdwlp1.uhbs.ch" class="external-link" rel="nofollow">ictthdbdwlp1.uhbs.ch</a>:33241)')</p><p><span style="font-size: 1.43em;">29.03.2023: CARDIOAPP</span></p><p>01:42:28: [SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4 cannot allocate enough memory: please check traces for further information</p><h2 id="CDWHoutages-28.03.2023:ISH">28.03.2023: ISH</h2><p>00:15:10: Error calling RFC function to get table data: &lt;RFC_COMMUNICATION_FAILURE- connection closed without message (CM_NO_DATA_RECEIVED)&gt;</p><p><span style="font-size: 1.43em;">27.03.2023: CATO, MOSAIQ, OSM (Openspecimen), ZAMD, MOLPATH, SEMA, COPRA, RADIMETRICS, ISOP</span></p><p>From 02:40:00 - 03:40:00: Due to change from winter to summer time, a CDWH-Flow was started at 2:40am. Since we have a check, that LZ are not started when a CDWH-Job is running, all LZ-Loads starting later than 2:40am failed.</p><p><span style="font-size: 1.43em;">09.03.2023: ISOP</span></p><p>03:25:24: Integrity constraint violation;301 unique constraint violated. See Hotfix-Issue: <a href="https://gitlab.uhbs.ch/cdwh/cdwh/-/issues/669" class="external-link" rel="nofollow">https://gitlab.uhbs.ch/cdwh/cdwh/-/issues/669</a></p><p><span style="font-size: 1.43em;">02.03.2023: BJ_LZ_MTTOOLS</span></p><p>02:51:09: Dataflow DF_LZ_MTT_V_AUSLASTUNG_GG<br/>ODBC call &lt;SQLDriverConnect&gt; for data source &lt;VMSQLMS03\MP8P&gt; failed: &lt;[Microsoft][ODBC SQL Server Driver][SQL Server]Cannot<br/>open database &quot;mttools&quot; requested by the login. The login failed.&gt;. Notify Customer Support.</p><h2 id="CDWHoutages-28.02.2023:DIM_ORG_HIER_COST_CENTER">28.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p>03:43:11: Task 'transformation_cdwh.dim_org_hier_cost_center: transform': Exception encountered during task execution!Traceback (most recent call last):  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&quot;, line 1900, in _execute_context    self.dialect.do_execute(  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy_hana/dialect.py&quot;, line 697, in wrapper    return f(dialect, *args, **kwargs)  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute    cursor.execute(statement, parameters)hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33333230412e3437\', pos=1814; indexname=_SYS_TREE_CS_#709153_#0_#P0')</p><h2 id="CDWHoutages-27.02.2023:DIM_ORG_HIER_COST_CENTER">27.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p>03:40:52: Task 'transformation_cdwh.dim_org_hier_cost_center: transform': Exception encountered during task execution!Traceback (most recent call last):  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&quot;, line 1900, in _execute_context    self.dialect.do_execute(  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy_hana/dialect.py&quot;, line 697, in wrapper    return f(dialect, *args, **kwargs)  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute    cursor.execute(statement, parameters)hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33333230412e3437\', pos=1814; indexname=_SYS_TREE_CS_#709153_#0_#P0')</p><h2 id="CDWHoutages-26.02.2023:DIM_ORG_HIER_COST_CENTER">26.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p>03:40:32: Task 'transformation_cdwh.dim_org_hier_cost_center: transform': Exception encountered during task execution!Traceback (most recent call last):  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&quot;, line 1900, in _execute_context    self.dialect.do_execute(  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy_hana/dialect.py&quot;, line 697, in wrapper    return f(dialect, *args, **kwargs)  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute    cursor.execute(statement, parameters)hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33333230412e3437\', pos=1814; indexname=_SYS_TREE_CS_#709153_#0_#P0')</p><h2 id="CDWHoutages-25.02.2023:DIM_ORG_HIER_COST_CENTER">25.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p>03:40:29: Task 'transformation_cdwh.dim_org_hier_cost_center: transform': Exception encountered during task execution!Traceback (most recent call last):  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&quot;, line 1900, in _execute_context    self.dialect.do_execute(  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy_hana/dialect.py&quot;, line 697, in wrapper    return f(dialect, *args, **kwargs)  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute    cursor.execute(statement, parameters)hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33333230412e3437\', pos=1814; indexname=_SYS_TREE_CS_#709153_#0_#P0')</p><h2 id="CDWHoutages-24.02.2023:DIM_ORG_HIER_COST_CENTER">24.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p>03:40:30: Task 'transformation_cdwh.dim_org_hier_cost_center: transform': Exception encountered during task execution!Traceback (most recent call last):  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&quot;, line 1900, in _execute_context    self.dialect.do_execute(  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy_hana/dialect.py&quot;, line 697, in wrapper    return f(dialect, *args, **kwargs)  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute    cursor.execute(statement, parameters)hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33333230412e3437\', pos=1814; indexname=_SYS_TREE_CS_#709153_#0_#P0')</p><h2 id="CDWHoutages-23.02.2023:DIM_ORG_HIER_COST_CENTER">23.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p>03:40:29: Task 'transformation_cdwh.dim_org_hier_cost_center: transform': Exception encountered during task execution!Traceback (most recent call last):  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&quot;, line 1900, in _execute_context    self.dialect.do_execute(  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy_hana/dialect.py&quot;, line 697, in wrapper    return f(dialect, *args, **kwargs)  File &quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute    cursor.execute(statement, parameters)hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33333230412e3437\', pos=1814; indexname=_SYS_TREE_CS_#709153_#0_#P0')</p><h2 id="CDWHoutages-22.02.2023:DIM_ORG_HIER_COST_CENTER">22.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p><span><span class="legacy-color-text-default"><span><span data-colorid="s1b7qoepuj">03:40:31</span>: </span></span>hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33383230462e3437\', pos=1816; indexname=_SYS_TREE_CS_#709153_#0_#P0')</span></p><h2 id="CDWHoutages-21.02.2023:CARDIOAPP">21.02.2023: CARDIOAPP</h2><p>Fehler beim LZ-Load.</p><p>There was an error in the workflow 'WF_LZ_CAR', -1 ) &gt; failed, due to error &lt;50316&gt;:</p><h2 id="CDWHoutages-21.02.2023:DIM_ORG_HIER_COST_CENTER">21.02.2023: DIM_ORG_HIER_COST_CENTER</h2><p><span><span class="legacy-color-text-default"><span><span data-colorid="aux7ff6zhv">03:40:31</span>: </span></span>hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 388): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_DIM_ORG_HIER_COST_CENTER&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): Table(TZ_DIM_ORG_HIER_COST_CENTER), Index(_SYS_TREE_CS_#709153_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_DIM_ORG_HIER_COST_CENTERen, constraint=\'ORG_HIER_COST_CENTER_LL_BK\', udiv=\'33383230462e3437\', pos=1816; indexname=_SYS_TREE_CS_#709153_#0_#P0')</span></p><h2 id="CDWHoutages-17.02.2023-21.02.2023:SENTRYSUITE">17.02.2023 - 21.02.2023: SENTRYSUITE</h2><p>Änderung an Tabellen Labuser und Patient wurden auf Quellseite vorgenommen. Dies führte zu Fehlern beim LZ-Load.</p><h2 id="CDWHoutages-30.01.2023:COPRA">30.01.2023: COPRA</h2><p><span class="legacy-color-text-default"><span data-colorid="1svqp3asg2">Die Backup-Datenbank war nicht parat.</span></span></p><p><span class="legacy-color-text-default"><span><span data-colorid="m8kq4j0epz">03:40:30</span>: Task 'transformation_cdwh.dim_fluid_balance_type: transform': Exception encountered during task execution! Traceback (most recent call last): File &quot;/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py&quot;, line 880, in get_task_run_state value = prefect.utilities.executors.run_task_with_timeout( File &quot;/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py&quot;, line 468, in run_task_with_timeout return task.run(*args, **kwargs) # type: ignore File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/generic/db_transformation.py&quot;, line 112, in transform entity.check_dependencies(dependency_valid_window_h) File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/db_base.py&quot;, line 186, in check_dependencies raise Exception(msg) Exception: Dependencies for table &quot;v_tz_dim_fluid_balance_type&quot; are not ready (dependency_valid_window_h=8). This are the data from the LZ Job for this Table: table=WF_LZ_COP_CO6_CONFIG_VARIABLES, start_loading=2023-01-29 02:55:19, status=end table=WF_LZ_COP_CO6_CONFIG_VARIABLETYPES, start_loading=2023-01-29 02:55:19, status=end</span></span></p><h2 id="CDWHoutages-27.01.2023:COPRA">27.01.2023: COPRA</h2><p><span class="legacy-color-text-default"><span data-colorid="n9uq143n7l">Die Backup-Datenbank war nicht parat.</span></span></p><h2 id="CDWHoutages-26.01.2023:COPRA">26.01.2023: COPRA</h2><p><span data-colorid="ewcrgephmk">03:40:30</span>: <span>Task 'transformation_c</span><span style="font-size: 14.0px;">dwh.fct_fluid_balance_metavision: transform': Exception encountered during task execution! Traceback (most recent call last): File &quot;/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py&quot;, line 880, in get_task_run_state value = prefect.utilities.executors.run_task_with_timeout( File &quot;/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py&quot;, line 468, in run_task_with_timeout return task.run(*args, **kwargs) # type: ignore File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/generic/db_transformation.py&quot;, line 112, in transform entity.check_dependencies(dependency_valid_window_h) File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/db_base.py&quot;, line 186, in check_dependencies raise Exception(msg) Exception: Dependencies for table &quot;v_tz_fct_fluid_balance_metavision&quot; are not ready (dependency_valid_window_h=8). This are the data from the LZ Job for this Table: table=WF_LZ_COP_CO6_CONFIG_VARIABLES, start_loading=2023-01-25 09:49:36, status=end table=WF_LZ_COP_CO6_CONFIG_VARIABLETYPES, start_loading=2023-01-25 09:49:36, status=end</span></p><h2 id="CDWHoutages-23.01.2023:COPRA">23.01.2023: COPRA</h2><p><span data-colorid="w4xt8u3atk">03:42:34</span>: <span>Task 'transformation_cdwh.dim_organsupport_values_copra: transform': Exception encountered during task execution! Traceback (most recent call last): File &quot;/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py&quot;, line 880, in get_task_run_state value = prefect.utilities.executors.run_task_with_timeout( File &quot;/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py&quot;, line 468, in run_task_with_timeout return task.run(*args, **kwargs) # type: ignore File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/generic/db_transformation.py&quot;, line 112, in transform entity.check_dependencies(dependency_valid_window_h) File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/db_base.py&quot;, line 186, in check_dependencies raise Exception(msg) Exception: Dependencies for table &quot;v_tz_dim_organsupport_values_copra&quot; are not ready (dependency_valid_window_h=8).</span></p><h2 id="CDWHoutages-19.01.2023:Servman,COPRA">19.01.2023: Servman, COPRA</h2><p><span><span data-colorid="kr0lab301e">03:41:03 : </span>Task 'transformation_cdwh.dim_organsupport_values_copra: transform': Exception encountered during task execution! Traceback (most recent call last): File &quot;/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py&quot;, line 880, in get_task_run_state value = prefect.utilities.executors.run_task_with_timeout( File &quot;/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py&quot;, line 468, in run_task_with_timeout return task.run(*args, **kwargs) # type: ignore File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/generic/db_transformation.py&quot;, line 112, in transform entity.check_dependencies(dependency_valid_window_h) File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/db_base.py&quot;, line 186, in check_dependencies raise Exception(msg) Exception: Dependencies for table &quot;v_tz_dim_organsupport_values_copra&quot; are not ready (dependency_valid_window_h=8).</span></p><p><span><span><span data-colorid="jda1vu4c6s">03:41:09 : </span>Task 'transformation_cdwh.fct_lep_activity_servman: transform': Exception encountered during task execution! Traceback (most recent call last): File &quot;/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py&quot;, line 880, in get_task_run_state value = prefect.utilities.executors.run_task_with_timeout( File &quot;/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py&quot;, line 468, in run_task_with_timeout return task.run(*args, **kwargs) # type: ignore File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/generic/db_transformation.py&quot;, line 112, in transform entity.check_dependencies(dependency_valid_window_h) File &quot;/usr/local/lib/python3.9/site-packages/cdwhprefect/model/task_collection/db_entity/db_base.py&quot;, line 186, in check_dependencies raise Exception(msg) Exception: Dependencies for table &quot;v_tz_fct_lep_activity_servman&quot; are not ready (dependency_valid_window_h=8). </span></span></p><h2 id="CDWHoutages-12.01.2023:CDWH-Load:MemoryIssueHANA">12.01.2023: CDWH-Load: Memory Issue HANA</h2><p>Exact time of error:  04:21</p><div><div><p><br/></p><p>cdwh:fct_document_healthengine,<br/>hdbcli.dbapi.Error: (2048, &quot;column store error: search table error: [2617] executor: plan operation execution failed with an exception;exception 6946: AttributeStoreFile error while deserializing from file '&lt;UT Main Column Reader&gt;': AttributeEngine: error reading file\n,Exception in executor plan1144471939@ictshdblp08:33240 while executing pop 27: (at pos 283) &quot;)</p><p>fct_form_ismed<br/>hdbcli.dbapi.InternalError: (129, 'transaction rolled back by an internal error: &quot;CDWH&quot;.&quot;LIB_FCT_FORM_ISMED&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 566): Allocation failed ; $size$=30146672; $name$=TableUpdate; $type$=pool; $inuse_count$=104033; $allocated_size$=25237813771; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)')</p><p>,fct_labor_result_xlab<br/>Error during execution of task: OperationalError('(hdbcli.dbapi.OperationalError) (4, \'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information\')')</p><h2 id="CDWHoutages-11.01.2023:CDWH-Load:MemoryIssueHANA">11.01.2023: CDWH-Load: Memory Issue HANA</h2><p><span class="text-caption">[11 Jan 2023 4:23am]<span> transformation_cdwh.fct_labor_result_xlab: transform </span></span></p><p><span>Error during execution of task: OperationalError('(hdbcli.dbapi.OperationalError) (4, \'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information\')')</span></p></div><h2 id="CDWHoutages-10.01.2023:CDWH-Load:MemoryIssueHANA">10.01.2023: CDWH-Load: Memory Issue HANA</h2><p><span class="text-caption">[10 Jan 2023 4:17am] transformation_cdwh.fct_labor_result_xlab: transform </span></p><p><span>Error during execution of task: OperationalError('(hdbcli.dbapi.OperationalError) (4, \'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information\')')</span></p></div><p><span><span class="text-caption">[10 Jan 2023 4:17am] transformation_cdwh.fct_form_ismed: transform <span> </span></span></span></p><p><span><span>Error during execution of task: InternalError('(hdbcli.dbapi.InternalError) (129, \'transaction rolled back by an internal error: &quot;CDWH&quot;.&quot;LIB_FCT_FORM_ISMED&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 566): Allocation failed ; $size$=75888656; $name$=0xfe3a1c164d; $type$=pool; $inuse_count$=6278; $allocated_size$=6695968826; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)\\nAllocation failed ; $size$=87934992; $name$=0xfe3a1c164d; $type$=pool; $inuse_count$=6278; $allocated_size$=6695968826; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)\')')</span></span></p><h2 id="CDWHoutages-09.01.2023:COPRA&amp;CDWH-Load:MemoryIssueHANA">09.01.2023: COPRA &amp; CDWH-Load: Memory Issue HANA</h2><p>[09.01.2023 04:16:10] <strong>transformation_cdwh.fct_labor_result_xlab: transform:</strong></p><pre>hdbcli.dbapi.OperationalError: (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information')</pre><pre>sqlalchemy.exc.OperationalError: (hdbcli.dbapi.OperationalError) (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information')</pre><pre>[SQL: CALL cdwh.lib_fct_labor_result_xlab:tz_persist_vtz(1001413, 'LRX_RESULT_DATE_TS', 'TO_CHAR(NEXT_DAY(LAST_DAY(ADD_MONTHS(CURRENT_TIMESTAMP,-13))),''YYYY-MM-DD'')')]</pre><h2 id="CDWHoutages-08.01.2023:CDWH-Load:MemoryIssueHANA">08.01.2023: CDWH-Load: Memory Issue HANA</h2><p>[08.01.2023 04:19:16] <strong>transformation_cdwh.fct_labor_result_xlab: transform:</strong></p><pre>hdbcli.dbapi.OperationalError: (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information')</pre><pre>sqlalchemy.exc.OperationalError: (hdbcli.dbapi.OperationalError) (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information')</pre><pre>[SQL: CALL cdwh.lib_fct_labor_result_xlab:tz_persist_vtz(1001411, 'LRX_RESULT_DATE_TS', 'TO_CHAR(NEXT_DAY(LAST_DAY(ADD_MONTHS(CURRENT_TIMESTAMP,-13))),''YYYY-MM-DD'')')]</pre><h2 id="CDWHoutages-07.01.2023:COPRA&amp;CDWH-Load:MemoryIssueHANA">07.01.2023: COPRA &amp; CDWH-Load: Memory Issue HANA</h2><p>[07.01.2023 04:17:38] <strong>transformation_cdwh.fct_vital_values_meona: transform:</strong></p><pre>hdbcli.dbapi.InternalError: (129, 'transaction rolled back by an internal error: &quot;CDWH&quot;.&quot;LIB_FCT_VITAL_VALUES_MEONA&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 582): Allocation failed ; $size$=110321680; $name$=0xfe3a060636; $type$=pool; $inuse_count$=8514; $allocated_size$=9031714784; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)')</pre><pre>sqlalchemy.exc.InternalError: (hdbcli.dbapi.InternalError) (129, 'transaction rolled back by an internal error: &quot;CDWH&quot;.&quot;LIB_FCT_VITAL_VALUES_MEONA&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 582): Allocation failed ; $size$=110321680; $name$=0xfe3a060636; $type$=pool; $inuse_count$=8514; $allocated_size$=9031714784; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)')</pre><pre>[SQL: CALL cdwh.lib_fct_vital_values_meona:tz_persist_vtz(1001409)]<br/><br/></pre><p>[07.01.2023 04:19:11] <strong>transformation_cdwh.fct_labor_result_xlab: transform:</strong></p><pre>hdbcli.dbapi.OperationalError: (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information')</pre><pre>sqlalchemy.exc.OperationalError: (hdbcli.dbapi.OperationalError) (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691): please check traces for further information')</pre><pre>[SQL: CALL cdwh.lib_fct_labor_result_xlab:tz_persist_vtz(1001409, 'LRX_RESULT_DATE_TS', 'TO_CHAR(NEXT_DAY(LAST_DAY(ADD_MONTHS(CURRENT_TIMESTAMP,-13))),''YYYY-MM-DD'')')]</pre><h2 id="CDWHoutages-29.12.2022:COPRA:Backupdatenbanknichtverfügbar">29.12.2022: COPRA<span>: Backupdatenbank nicht verfügbar</span></h2><p>Exact time of error: 03:10:14</p><p>ODBC data source &lt;ictsqlcdwhwp01\CDWHP&gt; error message for operation &lt;SQLExecute&gt;: &lt;[Microsoft][ODBC SQL Server Driver]Communication link failure&gt;.</p><h2 id="CDWHoutages-29.12.2022:Healthengine,ISHundCardioapp">29.12.2022: Healthengine, ISH und Cardioapp</h2><p>Exact time of error: 00:09:30</p><p>SAP HANA Memory Allocation failure</p><h2 id="CDWHoutages-28.12.2022:Cardioapp,PEP,LIS">28.12.2022: Cardioapp, PEP, LIS</h2><p>Exact time of error: 01:38:47 - 01:51:58</p><p>SAP HANA Memory Allocation failure</p><h2 id="CDWHoutages-27.12.2022:COPRA:Backupdatenbanknichtverfügbar">27.12.2022: COPRA<span>: Backupdatenbank nicht verfügbar</span></h2><p>Exact time of error: 03:10:18</p><p>ODBC data source &lt;ictsqlcdwhwp01\CDWHP&gt; error message for operation &lt;SQLExecute&gt;: &lt;[Microsoft][ODBC SQL Server Driver]Communication link failure&gt;.</p><h2 id="CDWHoutages-24.12.2022:COPRA:Backupdatenbanknichtverfügbar">24.12.2022: COPRA<span>: Backupdatenbank nicht verfügbar</span></h2><p>Exact time of error: 03:10:14</p><p>ODBC data source &lt;ictsqlcdwhwp01\CDWHP&gt; error message for operation &lt;SQLExecute&gt;: &lt;[Microsoft][ODBC SQL Server Driver]Communication link failure&gt;.</p><h2 id="CDWHoutages-24.12.2022:Healthengine,ISMED,Cardioapp,Pathowin,SentrySuite">24.12.2022: Healthengine, ISMED, Cardioapp, Pathowin, SentrySuite</h2><p>Exact time of error: 03:10:15</p><p>SAP HANA Memory Allocation failure</p><p><span style="font-size: 1.43em;">22.12.2022: COPRA: Backupdatenbank nicht verfügbar</span></p><p>Exact time of error: 03:10:15</p><p>ODBC data source &lt;ictsqlcdwhwp01\CDWHP&gt; error message for operation &lt;SQLExecute&gt;: &lt;[Microsoft][ODBC SQL Server Driver]Communication link failure&gt;.</p><h2 id="CDWHoutages-19.12.2022:AlleLZundCDWH-Jobs">19.12.2022: Alle LZ und CDWH-Jobs</h2><p>Exact time of error: Die ganze Nacht</p><p>InternalError(&quot;(hdbcli.dbapi.InternalError) (129, 'transaction rolled back by an internal error: CompileServerNotFoundException')&quot;)</p><h2 id="CDWHoutages-12.12.2022:SERVMAN">12.12.2022: SERVMAN</h2><p>Exact time of error: 22:07:10</p><p>&lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;129 transaction rolled back by an internal error: Allocation failed ; $size$=56160; $name$=LeafNodes; $type$=pool; $inuse_count$=218675; $allocated_size$=2843018840; $alignment$=8;<br/>$failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit) Allocation failed ; $size$=52320; $name$=LeafNodes; $type$=pool; $inuse_count$=218675; $allocated_size$=2843018840; $alignment$=8;<br/>$failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)&gt;.</p><h2 id="CDWHoutages-11.12.2022:CDWH-Load:MemoryIssueHANA">11.12.2022: CDWH-Load: Memory Issue HANA</h2><p>Exact time of error: 04:17:52</p><p><span class="legacy-color-text-default"><span class="legacy-color-text-blue1">CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ:</span><br/><span class="legacy-color-text-blue1">hdbcli.dbapi.OperationalError: (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691):<br/>search table error: [9] Memory allocation failed;exception 1000002: Allocation failed ; $size$=13839600000; $name$=Results; $type$=pool; $inuse_count$=590; $allocated_size$=388741526244; $alignment$=8;<br/>$failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$=\n,Exception in executor plan1058287822@ictshdblp08:33240 while executing pop 25')</span><br/></span></p><h2 id="CDWHoutages-09.12.2022:CDWH-Load:MemoryIssueHANA">09.12.2022: CDWH-Load: Memory Issue HANA</h2><p>Exact time of error: 04:20:53</p><p><span class="legacy-color-text-default">CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ:</span></p><p><span class="legacy-color-text-default">hdbcli.dbapi.OperationalError: (4, 'cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 34 col 3 (at pos 1691):<br/>search table error: [9] Memory allocation failed;exception 1000002: Allocation failed ; $size$=13834361344; $name$=Results; $type$=pool; $inuse_count$=464; $allocated_size$=480884216580; $alignment$=8;<br/>$failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$=\n,Exception in executor plan1053012890@ictshdblp08:33240 while executing pop 25')</span></p><h2 id="CDWHoutages-07.12.2022:CLABSIAPP">07.12.2022: CLABSIAPP</h2><p><span class="legacy-color-text-default">Exact time of error: 03:40:38</span></p><p><span class="legacy-color-text-default">hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated: &quot;CDWH&quot;.&quot;LIB_FCT_INFECTION_EPISODE_RESULT_CLABSIAPP&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 10 col 7 (at pos 402): unique constraint violated: &quot;CDWH&quot;.&quot;LIB_FCT_INFECTION_EPISODE_RESULT_CLABSIAPP&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 614): Table(TZ_FCT_INFECTION_EPISODE_RESULT_CLABSIAPP), Index(_SYS_TREE_CS_#9017079_#0_#P0) with error: unique constraint violation in self check for table DWHP::CDWH:TZ_FCT_INFECTION_EPISODE_RESULT_CLABSIAPPen, constraint=\'IRCL_BK\', udiv=\'34373738363234307c3134313638307c32\', pos=146; indexname=_SYS_TREE_CS_#9017079_#0_#P0').</span></p><p><span class="legacy-color-text-default">Devon is informed about the error.</span></p><h2 id="CDWHoutages-04.12.2022:CARDIOAPP"><span class="legacy-color-text-default">04.12.2022: CARDIOAPP</span></h2><p>Exact time of error: 02:44:10</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4 cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_4DE91_CV_LDR&quot;: line 6 col 1 (at pos 177):<br/>search table error: [9] Memory allocation failed;exception 1000002: Allocation failed ; $size$=71674557888; $name$=Results; $type$=pool; $inuse_count$=1386; $allocated_size$=1918391402448; $alignment$=8;<br/>$failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= ,Exception in executor plan1039275457@ictshdblp08:33240 while executing pop 18&gt;</p><h2 id="CDWHoutages-02.12.2022:MemoryIssueHANA">02.12.2022: Memory Issue HANA</h2><p>Exact time of error: 04:08:52</p><p>We got these errors:</p><ul><li>cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_LABOR_RESULT_XLAB&quot;:&quot;TZ_PERSIST_VTZ&quot;</li><li>transaction rolled back by an internal error: &quot;CDWH&quot;.&quot;LIB_DIM_HIER_HORIZONTAL_SNOMED&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 590): Allocation failed ; $size$=31457378; $name$=UpdateContext_TempAlloc; $type$=TempAllocator; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)</li><li>cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_APPOINTMENT_RAP&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 576): please check traces for further information</li><li>cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_UDF_MEONA&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 564): please check traces for further information</li><li>cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_VITAL_VALUES_MEONA&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 582): search table error: [9] Memory allocation failed;exception 1000002: Allocation failed ; $size$=424; $name$=EvaluatorMergeCommonParts; $type$=TempAllocator; $alignment$=8; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)\n,Exception in executor plan1032963441@ictshdblp08:33240 while executing pop 8</li><li>cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_ORGANSUPPORT_VALUES_COPRA&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 596): please check traces for further information</li><li>cannot allocate enough memory: &quot;CDWH&quot;.&quot;LIB_FCT_ACCESS_DEVICES_MEONA&quot;:&quot;TZ_PERSIST_VTZ&quot;: line 15 col 3 (at pos 586): search table error: [9] Memory allocation failed;exception 1000002: Allocation failed ; $size$=624; $name$=TempAlloc; $type$=TempAllocator; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)\n,Exception in executor plan1032965074@ictshdblp08:33240 while executing pop 8</li></ul><p>All of them because OOM's.</p><p><br/></p><p><span style="font-size: 1.43em;">04.11.2022: CARDIOAPP</span></p><p>Exact time of error: 01:29:24</p><p>SQL submitted to database &lt;&gt; resulted in error &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4 cannot allocate enough memory: OOM. please check traces for further information&gt;. The SQL submitted is &lt;INSERT INTO CARDIOAPP.FCT_EXAMINATION_VALUES_CARDIOAPP select 633227, EVC_BK, EVC_SYS_NK, EXC_BK, EPC_CODE_NK, EVC_AGGR_NK, EVC_CONT_NK, EVC_LINE_NK, EVC_SUB_FORM_OBJ_NK, PAT_BK, PAT_INT_ID, CAS_BK, EPC_BK, EPC_ID, EVC_NUMERIC_VALUE, EVC_TEXT_VALUE, EVC_UNIT_ID, EVC_DATE_VALUE, EVC_EXAMINATION_DATE_TS, EVC_CREATE_DATE_TS, EVC_UPDATE_DATE_TS, PFORM_OBJID, VIEWFORM_OBJID, OBJ_SUB_VALUE_INT, A_VALUE_INT, OBJ_SUB_VALUE_FLO, A_VALUE_FLO, OBJ_SUB_VALUE_STR, A_VALUE_STR, A2_STRVAL, OBJ_SUB_VALUE_DATE, A_VALUE_DATE, AGG_VALUE_AGG, AGG2_VALUE_AGG, PITEMTAB_STRVAL, A_ATTR_REF, OBJ_SUB_ATTR_REF, A_OBJID, A_ATTRID, A_AGGRID, A_LINEID from CARDIOAPP.V_FCT_EXAMINATION_VALUES_CARDIOAPP WITH hint (no_cs_join)&gt;</p><p><span style="font-size: 1.43em;">27.09.2022: CARDIOAPP</span></p><p>Exact time of error: 01:35:21</p><p>SQL submitted to database &lt;&gt; resulted in error &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4 cannot allocate enough memory: OOM. please check traces for further information&gt;.<br/>The SQL submitted is &lt;INSERT INTO CARDIOAPP.FCT_EXAMINATION_VALUES_CARDIOAPP select 605926, EVC_BK, EVC_SYS_NK, EXC_BK, EPC_CODE_NK, EVC_AGGR_NK, EVC_CONT_NK, EVC_LINE_NK,<br/>EVC_SUB_FORM_OBJ_NK, PAT_BK, PAT_INT_ID, CAS_BK, EPC_BK, EPC_ID, EVC_NUMERIC_VALUE, EVC_TEXT_VALUE, EVC_UNIT_ID, EVC_DATE_VALUE, EVC_EXAMINATION_DATE_TS, EVC_CREATE_DATE_TS,<br/>EVC_UPDATE_DATE_TS, PFORM_OBJID, VIEWFORM_OBJID, OBJ_SUB_VALUE_INT, A_VALUE_INT, OBJ_SUB_VALUE_FLO, A_VALUE_FLO, OBJ_SUB_VALUE_STR, A_VALUE_STR, A2_STRVAL, OBJ_SUB_VALUE_DATE,<br/>A_VALUE_DATE, AGG_VALUE_AGG, AGG2_VALUE_AGG, PITEMTAB_STRVAL, A_ATTR_REF, OBJ_SUB_ATTR_REF, A_OBJID, A_ATTRID, A_AGGRID, A_LINEID <br/>from CARDIOAPP.V_FCT_EXAMINATION_VALUES_CARDIOAPP WITH hint (no_cs_join)&gt;</p><h2 id="CDWHoutages-26.09.2022:PATHOWIN">26.09.2022: PATHOWIN</h2><p>Exact time of error: 01:02:11</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecute&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] Connection not open;<br/>-10807 System call 'send' failed, rc=10053:An established connection was aborted by the software in your host machine</p><h2 id="CDWHoutages-26.09.2022:HEALTHENGINE">26.09.2022: HEALTHENGINE</h2><p>Exact time of error: 01:02:11</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecute&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] Connection not open;<br/>-10807 System call 'send' failed, rc=10053:An established connection was aborted by the software in your host machine {10.5.67.138:33241}&gt;</p><h2 id="CDWHoutages-26.09.2022:CARDIOAPP">26.09.2022: CARDIOAPP</h2><p>Exact time of error: 01:52:59</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_6F451_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory allocation failed;<br/>exception 1000002: Allocation failed ; $size$=4124530016; $name$=TranslationTable; $type$=pool; $inuse_count$=8257;<br/>$allocated_size$=187302053624; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= exception 1000002: Allocation failed ; <br/>$size$=4124530016; $name$=TranslationTable; $type$=pool; $inuse_count$=8257; $al&gt;</p><h2 id="CDWHoutages-25.09.2022:CARDIOAPP">25.09.2022: CARDIOAPP</h2><p>Exact time of error: 01:40:30</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_5A671_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory allocation failed;<br/>exception 1000002: Allocation failed ; $size$=65920790272; $name$=Results; $type$=pool; $inuse_count$=915; $allocated_size$=1432924178144;<br/>$alignment$=8; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= ,Exception in executor plan845521512@ictshdblp08:33240 while executing pop 19&gt;</p><h2 id="CDWHoutages-24.09.2022:CARDIOAPP">24.09.2022: CARDIOAPP</h2><p>Exact time of error: 01:30:15</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_14821_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory allocation failed;<br/>exception 1000002: Allocation failed ; $size$=3740479488; $name$=Results; $type$=pool; $inuse_count$=715; $allocated_size$=1625350645052;<br/>$failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit) ,Exception in executor plan843260443@ictshdblp08:33240 while executing pop 16&gt;</p><h2 id="CDWHoutages-22.09.2022:CARDIOAPP">22.09.2022: CARDIOAPP</h2><p>Exact time of error: 01:17:19</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_33051_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory allocation failed;<br/>exception 1000002: Allocation failed ; $size$=65632925312; $name$=Results; $type$=pool; $inuse_count$=291; $allocated_size$=1610707515184;<br/>$alignment$=8; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= ,Exception in executor plan838059615@ictshdblp08:33240 while executing pop 18&gt;</p><h2 id="CDWHoutages-21.09.2022:CARDIOAPP">21.09.2022: CARDIOAPP</h2><p>Exact time of error: 01:41:58</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_33101_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory<br/>allocation failed;exception 1000002: Allocation failed ; $size$=2147483648; $name$=NTuple; $type$=pool; $inuse_count$=1512;<br/>$allocated_size$=233149536564; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= exception 1000002: Allocation failed ;<br/>$size$=2147483648; $name$=NTuple; $type$=pool; $inuse_count$=1512; $allocated_size$=233149&gt;</p><h2 id="CDWHoutages-19.09.2022:CARDIOAPP">19.09.2022: CARDIOAPP</h2><p>Exact time of error: 01:45:58</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_65481_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory<br/>allocation failed;exception 1000002: Allocation failed ; $size$=123671104; $name$=Results; $type$=pool; $inuse_count$=1767;<br/>$allocated_size$=2159027511160; $alignment$=16; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)<br/>,Exception in executor plan619886541@ictshdblp08:33240 while executing pop 18&gt;.</p><h2 id="CDWHoutages-18.09.2022:CARDIOAPP">18.09.2022: CARDIOAPP</h2><p>Exact time of error: 01:28:06</p><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_65481_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory<br/>allocation failed;exception 1000002: Allocation failed ; $size$=123671104; $name$=Results; $type$=pool; $inuse_count$=1767;<br/>$allocated_size$=2159027511160; $alignment$=16; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)<br/>,Exception in executor plan619886541@ictshdblp08:33240 while executing pop 18&gt;.</p><h2 id="CDWHoutages-16.09.2022:BLUES">16.09.2022: BLUES</h2><p>Exact time of error: 01:40:09<br/>There was a table lock on SAP HANA Database.<br/>1st try to reload in the morning had the same error again, another reload went fine.</p><p>[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;131 transaction rolled back by lock wait timeout:<br/>Lock-wait time out exceeded [OWNER=5908232127, TYPE=OBJECT_LOCK, CURRENT_MODE=INTENTIONAL_EXCLUSIVE, REQUESTED_MODE=EXCLUSIVE]&gt;.<br/>The SQL submitted is &lt;TRUNCATE TABLE &quot;BLUES&quot;.&quot;BEWEGUNGEN&quot;</p><h2 id="CDWHoutages-16.09.2022:CARDIOAPP">16.09.2022: CARDIOAPP</h2><p>Exact time of error: 00:08:18<br/>Unknown error without reasonable error message.<br/>The reload in the morning ran through without any problems.<br/>ODBC data source &lt;CLSQL1203\CAP&gt; error message for operation &lt;SQLFreeStmt&gt;: &lt;&gt;.</p><h2 id="CDWHoutages-15.09.2022:Meona,MTTOOLS,ZAMD,Molpath">15.09.2022: Meona, MTTOOLS, ZAMD, Molpath</h2><p>Exact time of error: 02:54:00 - 02:57:00<br/>OOM (out of memory): 37 times on the server, internal backup jobs waited, P11 Table growth,...</p><div class="code panel pdl" style="border-width: 1px;"><div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: java; gutter: false; theme: Confluence" data-theme="Confluence">&lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;129 transaction rolled back by an internal error:
Allocation failed ; $size$=52320; $name$=LeafNodes; $type$=pool; $inuse_count$=687195; $allocated_size$=15056466920; $alignment$=8; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$=(early exit)&gt;.</pre>
</div></div><p>Beim LZ nachladen, leider vergessen, dass auch auf Seite 2 Jobs gefailt haben. Darum erst um 14:30 Uhr vollständig geladen.</p><h2 id="CDWHoutages-20.08.2022:CARDIOAPP">20.08.2022: CARDIOAPP</h2><p>Exact time of error: 00:08:02<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-19.08.2022:CARDIOAPP">19.08.2022: CARDIOAPP</h2><p>Exact time of error: 00:15:18<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-16.08.2022:CARDIOAPP">16.08.2022: CARDIOAPP</h2><p>Exact time of error: 00:07:40<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-13.08.2022:CARDIOAPP">13.08.2022: CARDIOAPP</h2><p>Exact time of error: 00:12:23<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-09.08.2022:CARDIOAPP"><span style="letter-spacing: -0.008em;">09.08.2022: CARDIOAPP</span></h2><p>Exact time of error: 00:08:15<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-08.08.2022:CARDIOAPP">08.08.2022: CARDIOAPP</h2><p>Exact time of error: 00:12:43<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-06.08.2022-08.08.2022:SERVMAN"><span style="letter-spacing: -0.008em;">06.08.2022 - 08.08.2022: SERVMAN</span></h2><p>No access to 2 views on Servman-Database during 3 days: dbo.IBIVW_IntervalleLEPN3 and dbo.IBIVW_BenutzerLEPN3<br/><br/>[Microsoft][ODBC SQL Server Driver][SQL Server]The SELECT permission was denied on the object 'tblSchichten', database 'dbcareV5_Reporting', schema 'dbo'.&gt;. The SQL submitted is &lt;SELECT<br/> &quot;IBIVW_INTERVALLELEPN3&quot;.&quot;STATION_ORG&quot; ,&quot;IBIVW_INTERVALLELEPN3&quot;.&quot;INTERVALLID&quot; , &quot;IBIVW_INTERVALLELEPN3&quot;.&quot;INTERVALL&quot; , &quot;IBIVW_INTERVALLELEPN3&quot;.&quot;INTERVALL_START_TIMESTAMP&quot; ,<br/> &quot;IBIVW_INTERVALLELEPN3&quot;.&quot;INTERVALL_ENDE_TIMESTAMP&quot; , &quot;IBIVW_INTERVALLELEPN3&quot;.&quot;INTERVALLGUID&quot; FROM &quot;EXT&quot;.&quot;IBIVW_INTERVALLELEPN3&quot; &quot;IBIVW_INTERVALLELEPN3&quot;<br/><br/>[Microsoft][ODBC SQL Server Driver][SQL Server]The SELECT permission was denied on the object 'Benutzer', database 'dbcareV5_Reporting', schema 'dbo'.&gt;. The SQL submitted is<br/> &lt;SELECT &quot;IBIVW_BENUTZERLEPN3&quot;.&quot;BENUTZER_GUID&quot; ,&quot;IBIVW_BENUTZERLEPN3&quot;.&quot;BENUTZER_USERNAME&quot; , &quot;IBIVW_BENUTZERLEPN3&quot;.&quot;BENUTZER_PERSONALNUMMER&quot; ,<br/> &quot;IBIVW_BENUTZERLEPN3&quot;.&quot;BENUTZER_PEPKENNUNG&quot; FROM &quot;EXT&quot;.&quot;IBIVW_BENUTZERLEPN3&quot; &quot;IBIVW_BENUTZERLEPN3&quot;</p><h2 id="CDWHoutages-06.08.2022:CARDIOAPP">06.08.2022: CARDIOAPP</h2><p>Exact time of error: 01:43:42<br/>[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4 cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_3E641_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory<br/>allocation failed;exception 1000002: Allocation failed ; $size$=64051052416; $name$=Results; $type$=pool; $inuse_count$=1331;<br/>$allocated_size$=1630740595488; $alignment$=8; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$=<br/>,Exception in executor plan697451444@ictshdblp08:33240 while executing pop 18</p><p><span style="font-size: 20.0px;letter-spacing: -0.008em;">31.07.2022: CARDIOAPP</span></p><p>Exact time of error: 00:17:21<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-30.07.2022:S4HANA">30.07.2022: S4HANA</h2><p>Exact time of error: 00:03:33<br/>Cannot create process with image file &lt;D:\SAP BusinessObjects\Data Services\bin\al_engine.exe&gt; and command line ←C&quot;D:\SAP<br/><span style="letter-spacing: 0.0px;">BusinessObjects\DS Common Dir\log/command_16104_07_30_2022_00_03_29__12&quot;&gt;, due to error &lt;Access is denied. &gt;.</span></p><h2 id="CDWHoutages-30.07.2022:ISH">30.07.2022: ISH</h2><p>Exact time of error: 00:03:33<br/><span style="letter-spacing: 0.0px;">Cannot create process with image file &lt;D:\SAP BusinessObjects\Data Services\bin\al_engine.exe&gt; and command line ←C&quot;D:\SAP<br/></span><span style="letter-spacing: 0.0px;">BusinessObjects\DS Common Dir\log/command_7748_07_30_2022_00_03_28__31&quot;&gt;, due to error &lt;Access is denied.</span><span style="letter-spacing: 0.0px;"><br/></span></p><h2 id="CDWHoutages-29.07.2022:CARDIOAPP">29.07.2022: CARDIOAPP</h2><p>Exact time of error: 00:12:48<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-28.07.2022:CARDIOAPP">28.07.2022: CARDIOAPP</h2><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4 cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_509D1_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory allocation failed;exception 1000002: Allocation failed ; $size$=3987313428; $name$=JEStep2; $type$=pool; $inuse_count$=11; $allocated_size$=3987676172; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= Exception in executor plan671474197@ictshdblp08:33240 while executing pop 2&gt;.</p><h2 id="CDWHoutages-25.07.2022:EXPORT_NORA">25.07.2022: EXPORT_NORA</h2><p>NORA-Datenbank nicht erreichbar.</p><h2 id="CDWHoutages-25.07.2022:CARDIOAPP">25.07.2022: CARDIOAPP</h2><p>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-23.07.2022:CARDIOAPP">23.07.2022: CARDIOAPP</h2><p>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-22.07.2022:CARDIOAPP">22.07.2022: CARDIOAPP</h2><p>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-17.07.2022:CARDIOAPP">17.07.2022: CARDIOAPP</h2><p>[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).<br/>[Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation.</p><h2 id="CDWHoutages-11.07.2022:PEP">11.07.2022: PEP</h2><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecute&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;129<br/>transaction rolled back by an internal error: Allocation failed ; $size$=305760000; $name$=ValueDict; $type$=pool;<br/>$inuse_count$=1620; $allocated_size$=13446670296; $alignment$=8; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early<br/>exit)&gt;.</p><h2 id="CDWHoutages-09.07.2022:CARDIOAPP">09.07.2022: CARDIOAPP</h2><p>ODBC data source &lt;ictthdbdwlp1&gt; error message for operation &lt;SQLExecDirect&gt;: &lt;[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4<br/>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_65481_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory<br/>allocation failed;exception 1000002: Allocation failed ; $size$=123671104; $name$=Results; $type$=pool; $inuse_count$=1767;<br/>$allocated_size$=2159027511160; $alignment$=16; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= (early exit)<br/>,Exception in executor plan619886541@ictshdblp08:33240 while executing pop 18&gt;.</p><h2 id="CDWHoutages-08.07.2022:CARDIOAPP">08.07.2022: CARDIOAPP</h2><p><span>Fehlermeldung: </span>cannot allocate enough memory: &quot;CDWH&quot;.&quot;DS_PROC_142C1_CV_LDR&quot;: line 6 col 1 (at pos 177): search table error: [9] Memory allocation failed;exception 1000002: Allocation failed ; $size$=63278715136; $name$=Results; $type$=pool; $inuse_count$=1202; $allocated_size$=1905317107364; $alignment$=8; $failure_type$=GLOBAL_ALLOCATION_LIMIT; $failure_flag$= ,Exception in executor plan613657099@ictshdblp08:33240 while executing pop 18</p><p>→ Job restarted und ist durchgelaufen</p><h2 id="CDWHoutages-03.07.2022:CARDIOAPP">03.07.2022: CARDIOAPP</h2><p>Netzwerk-Unterbruch: ODBC data source &lt;CLSQL1203\CAP&gt; error message for operation &lt;SQLFetchScroll(rowStsArray[])&gt;: &lt;[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).</p><h2 id="CDWHoutages-30.06.2022:COPRA"><span>30.06.2022: COPRA</span></h2><p><span>Backup-Datenbank ist nicht aktuell und hat noch den Stand vom Vortag. Das Team ICT-Datenbanken ist informiert, warten auf Feedback.</span></p><p><span>Fehlermeldung von Rémy: Write on &quot;\\ictsqlcdwhwp01\Replication$\COPRA6Live_Replication_1.bak&quot; failed: 59(An unexpected network error occurred.</span></p><h2 id="CDWHoutages-26.06.2022:CARDIOAPP">26.06.2022: CARDIOAPP</h2><p>Netzwerk-Unterbruch: ODBC data source &lt;CLSQL1203\CAP&gt; error message for operation &lt;SQLFetchScroll(rowStsArray[])&gt;: &lt;[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).</p><h2 id="CDWHoutages-24.06.2022METAVISION"><span>24.06.2022 METAVISION</span></h2><pre>Netzwerk-Unterbruch: [Microsoft][ODBC SQL Server Driver]Communication link failure&gt;</pre><h2 id="CDWHoutages-24.06.2022:CARDIOAPP">24.06.2022: CARDIOAPP</h2><p>Netzwerk-Unterbruch: ODBC data source &lt;CLSQL1203\CAP&gt; error message for operation &lt;SQLFetchScroll(rowStsArray[])&gt;: &lt;[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).</p><h2 id="CDWHoutages-23.06.2022:COPRA"><span>23.06.2022: COPRA</span></h2><p><span>Backup-Datenbank ist nicht aktuell und hat noch den Stand vom Vortag.<br/>Fehlermeldung von Rémy: Write on &quot;\\ictsqlcdwhwp01\Replication$\COPRA6Live_Replication_1.bak&quot; failed: 59(An unexpected network error occurred<br/></span></p><h2 id="CDWHoutages-23.06.2022:CARDIOAPP">23.06.2022: CARDIOAPP</h2><p>Netzwerk-Unterbruch: ODBC data source &lt;CLSQL1203\CAP&gt; error message for operation &lt;SQLFetchScroll(rowStsArray[])&gt;: &lt;[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).</p><h2 id="CDWHoutages-15.06.2022:CARDIOAPP">15.06.2022: CARDIOAPP</h2><p>Netzwerk-Unterbruch: ODBC data source &lt;CLSQL1203\CAP&gt; error message for operation &lt;SQLFetchScroll(rowStsArray[])&gt;: &lt;[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).</p><h2 id="CDWHoutages-12.06.2022:CARDIOAPP">12.06.2022: CARDIOAPP</h2><p>Netzwerk-Unterbruch: ODBC data source &lt;CLSQL1203\CAP&gt; error message for operation &lt;SQLFetchScroll(rowStsArray[])&gt;: &lt;[Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionRead (recv()).</p><h2 id="CDWHoutages-12.06.2022:COPRA"><span style="letter-spacing: -0.008em;">12.06.2022: COPRA</span></h2><h2 id="CDWHoutages-Backup-DatenbankistnichtaktuellundhatnochdenStandvomVortag.Kurt-PhilippunddasTeamICT-Datenbankensindinformiert,wartenaufFeedback."><span style="font-size: 14.0px;letter-spacing: 0.0px;">Backup-Datenbank ist nicht aktuell und hat noch den Stand vom Vortag. Kurt-Philipp und das Team ICT-Datenbanken sind informiert, warten auf Feedback.</span></h2><h2 id="CDWHoutages-08.06.2022:RIS">08.06.2022: RIS</h2><p>Fehlermeldung: ORA-03113: end-of-file on communication channel Process ID: 15732 Session ID: 774 Serial number: 39012<br/>Von der Quelle verursacht, Reload ist problemlos durchgelaufen.</p><h2 id="CDWHoutages-28.05.2022:Cardioapp">28.05.2022: Cardioapp</h2><p>Fehler im DS: LZ_CARDIOAPP: General network error.</p><h2 id="CDWHoutages-20.05.2022:S4H">20.05.2022: S4H</h2><p>DS Fehler: Cannot load table with the wrong number of columns. Table &quot;CSKS&quot; has &quot;104&quot; columns while the input schema &quot;CSKS&quot; has &quot;105&quot; columns. Ensure that the input matches the table schema.</p><p>WF_LZ_S4H_CSKS konnte nicht geladen werden weil, eine Spalte im Source Tbl nicht mehr vorhanden war. Es wurde auf dem DS PRod ein Hotfix installiert.</p><h2 id="CDWHoutages-16.05.2022:RIS">16.05.2022: RIS</h2><p>Fehlermeldung: Warning: Your system is running low on virtual memory. Total size is &quot;71679&quot;, available &quot;3386&quot;.</p><p>DF_LZ_RIS_A_UNTBEH_UEB, DF_LZ_RIS_A_ABRFALL_LEISTUNG,DF_LZ_RIS_A_UNTBEH_UEB_ALLE verbrauchen ca. 10 GB. Ursache wird abgeklärt. <a href="https://gitlab.uhbs.ch/cdwh/cdwh/-/issues/543" class="external-link" rel="nofollow">LZ RIS low memory issue</a></p><h2 id="CDWHoutages-03.05.2022:RIS">03.05.2022: RIS</h2><p>Fehlermeldung: &quot;ORA-03114: not connected to ORACLE&quot;<br/>Job am Morgen neu gestartet und ist dann erfolgreich durchgelaufen.</p><h2 id="CDWHoutages-19.04.2022:MEONA">19.04.2022: MEONA</h2><p>Fehlermeldung: [Microsoft][ODBC SQL Server Driver]Communication link failure<br/>LZ neu gestartet und ist dann durchgelaufen, vermutlich war das Netzwerk kurz weg.</p><h2 id="CDWHoutages-05.04.2022:SERVMAN">05.04.2022: SERVMAN</h2><p>Fehlermeldung: Transaction (Process ID 116) was deadlocked on lock resources with another process and has been chosen as the deadlock victim<br/>Es sieht so aus, als ob die Tagesende-Verarbeitung länger gelaufen ist als normal und sich dadurch mit unserem Lade-Fenster überschnitten hat. Der Reload ist auf Anhieb durchgelaufen. Das müssen wir abklären.</p><h2 id="CDWHoutages-29.03.2022:SERVMAN">29.03.2022: SERVMAN</h2><p>Fehlermeldung: Transaction (Process ID 116) was deadlocked on lock resources with another process and has been chosen as the deadlock victim<br/>Es sieht so aus, als ob die Tagesende-Verarbeitung länger gelaufen ist als normal und sich dadurch mit unserem Lade-Fenster überschnitten hat. Der Reload ist auf Anhieb durchgelaufen. Möglicherweise wurde der Zeitpunkt der TEV auch Dauerhaft verändert, wenn es wieder passiert, klären wir das ab.</p><h2 id="CDWHoutages-28.03.2022:ISMED">28.03.2022: ISMED</h2><p>Fehlermeldung: ORA-28000 the account is locked Gemäss Remi Jakubowski wurde die Datenbank während dem Wartungsfenster vom Wochenende von 11.2.0.4 auf 19c migriert. Dabei wurde die STBY-Datenbank auch neu aufgebaut, allerdings war die alte STBY noch vorhanden. Der Load hat die Verbindung zur alten DB aufgebaut, wo jedoch alle User blockiert waren. Remi hat die alte DB gestoppt und der Reload hat funktioniert.</p><h2 id="CDWHoutages-27.03.2022:MLAB,RIS,MEONA,RAP,PEP,METAVISION">27.03.2022: MLAB, RIS, MEONA, RAP, PEP, METAVISION</h2><p>Fehlermeldung: Memory Allocation failed<br/>Wegen der Zeitumstellung auf Sommerzeit, sind zuviele Jobs gleichzeitig losgelaufen. Diese erhöhte Parallelität hat zu Speicher-Problemen auf dem DS-Server geführt. Der Re-Run der Jobs hat geklappt und das Problem ist behoben.</p><h2 id="CDWHoutages-14.03.2022:LIS">14.03.2022: LIS</h2><p>DS-Fehler beim Delta-Insert: object name already exists: DS_PROC_19681_CV_LDR<br/>Seltene Konstellation, dass der Drop der temporären Prozeduren nicht geklappt hat in der Nacht zuvor (hier müsste die Prozedur angepasst werden, das die RT-Jobs ignoriert werden!), zudem ist es auch selten, dass Prozedurnamen doppelt vergeben werden. Die Drop-Prozedur wird auf nächsten Release angepasst.</p><h2 id="CDWHoutages-19.01.2022:METAVISION">19.01.2022: METAVISION</h2><p>METAVISION: MSSQL Restore hat nicht funktioniert (Speicherprobleme auf dem Backup-Server, weitere Infos folgen)</p><h2 id="CDWHoutages-12.01.2022:CARDIOAPP">12.01.2022: CARDIOAPP</h2><p>[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;4 cannot allocate enough memory: OOM. please check traces for further information&gt;. The SQL submitted is &lt;INSERT INTO CARDIOAPP.FCT_EXAMINATION_VALUES_CARDIOAPP select 420807, EVC_BK, EVC_SYS_NK, EXC_BK, EPC_CODE_NK, EVC_AGGR_NK, EVC_CONT_NK, EVC_LINE_NK, EVC_SUB_FORM_OBJ_NK, PAT_BK, PAT_INT_ID, CAS_BK, EPC_BK, EVC_NUMERIC_VALUE, EVC_TEXT_VALUE, EVC_UNIT_ID, EVC_DATE_VALUE, EVC_EXAMINATION_DATE_TS, EVC_CREATE_DATE_TS, EVC_UPDATE_DATE_TS, PFORM_OBJID, VIEWFORM_OBJID, OBJ_SUB_VALUE_INT, A_VALUE_INT, OBJ_SUB_VALUE_FLO, A_VALUE_FLO, OBJ_SUB_VALUE_STR, A_VALUE_STR, A2_STRVAL, OBJ_SUB_VALUE_DATE, A_VALUE_DATE, AGG_VALUE_AGG, AGG2_VALUE_AGG, PITEMTAB_STRVAL, A_ATTR_REF, OBJ_SUB_ATTR_REF, A_OBJID, A_ATTRID, A_AGGRID, A_LINEID from CARDIOAPP.V_FCT_EXAMINATION_VALUES_CARDIOAPP WITH hint (no_cs_join)</p><h2 id="CDWHoutages-09.12.2021:CDWH.LIB_DIM_MEDICAMENT_EQUIVALENT:TZ_PERSIST_VTZ">09.12.2021: CDWH.LIB_DIM_MEDICAMENT_EQUIVALENT:TZ_PERSIST_VTZ</h2><p>[23057] Internal error during join: invalid input;</p><h2 id="CDWHoutages-01.12.2021:SAPHANABackupoverflow">01.12.2021: SAPHANA Backup overflow</h2><p>Timeouts</p><h2 id="CDWHoutages-26.11.2021:CDWH.LIB_DIM_MEDICAMENT_EQUIVALENT:TZ_PERSIST_VTZ">26.11.2021: CDWH.LIB_DIM_MEDICAMENT_EQUIVALENT:TZ_PERSIST_VTZ</h2><p>[23057] Internal error during join: invalid input;</p><h2 id="CDWHoutages-25.11.2021:SENTRYSUITE">25.11.2021: SENTRYSUITE</h2><p>SENTRYSUITE: Connection lost</p><h2 id="CDWHoutages-02.11.2021:METAVISION">02.11.2021: METAVISION</h2><p>METAVISION: MSSQL Restore hat nicht funktioniert</p><h2 id="CDWHoutages-25.10.2021:SENTRYSUITE">25.10.2021: SENTRYSUITE</h2><p>SENTRYSUITE: Connection lost</p><h2 id="CDWHoutages-21.10.2021:SENTRYSUITE">21.10.2021: SENTRYSUITE</h2><p>SENTRYSUITE: Connection lost</p><h2 id="CDWHoutages-16.10.2021-19.10.2021:SAP-ISH">16.10.2021 - 19.10.2021: SAP-ISH</h2><p>SAP-ISH: Invalid Date Value</p><h2 id="CDWHoutages-01.09.2021:METAVISION">01.09.2021: METAVISION</h2><p>METAVISION: MSSQL Restore hat nicht funktioniert (Kein Speicher)</p><h2 id="CDWHoutages-30.08.2021:METAVISION,CARDIOAPP">30.08.2021: METAVISION, CARDIOAPP</h2><p>METAVISION: MSSQL Restore hat nicht funktioniert (Kein Speicher)<br/>CARDIOAPP: Network Error</p><h2 id="CDWHoutages-29.08.2021:CARDIOAPP">29.08.2021: CARDIOAPP</h2><p>CARDIOAPP: Network Error</p><h2 id="CDWHoutages-28.08.2021:CARDIOAPP">28.08.2021: CARDIOAPP</h2><p>CARDIOAPP: Network Error</p><h2 id="CDWHoutages-20.08.2021:CARDIOAPP,PATHOWIN">20.08.2021: CARDIOAPP, PATHOWIN</h2><p>CARDIOAPP: Network Error<br/>PATHOWIN: Snapshot-Erstellung hat nicht funktioniert</p><h2 id="CDWHoutages-15.08.2021:PATHOWIN">15.08.2021: PATHOWIN</h2><p>PATHOWIN: Snapshot-Erstellung hat nicht funktioniert</p><h2 id="CDWHoutages-14.08.2021:PATHOWIN">14.08.2021: PATHOWIN</h2><p>PATHOWIN: Snapshot-Erstellung hat nicht funktioniert</p><h2 id="CDWHoutages-12.08.2021:PATHOWIN,MEONA,LIS(IMEDHL7)">12.08.2021: PATHOWIN, MEONA, LIS (IMEDHL7)</h2><p>PATHOWIN: Snapshot-Erstellung hat nicht funktioniert<br/>MEONA: MSSQL Restore hat nicht funktioniert<br/>LIS: CDWH-Incident beim Insert aus der DELTA-Tabelle (Unique Contraint Violation)</p><h2 id="CDWHoutages-9.08.2021:PATHOWIN">9.08.2021: PATHOWIN</h2><p>PATHOWIN: Snapshot-Erstellung hat nicht funktioniert</p><h2 id="CDWHoutages-8.08.2021:PATHOWIN">8.08.2021: PATHOWIN</h2><p>PATHOWIN: Snapshot-Erstellung hat nicht funktioniert</p><style>[data-colorid="s1b7qoepuj"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="s1b7qoepuj"]{color:#776f62}[data-colorid="aux7ff6zhv"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="aux7ff6zhv"]{color:#776f62}[data-colorid="m8kq4j0epz"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="m8kq4j0epz"]{color:#776f62}[data-colorid="n9uq143n7l"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="n9uq143n7l"]{color:#776f62}[data-colorid="jda1vu4c6s"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="jda1vu4c6s"]{color:#776f62}[data-colorid="w4xt8u3atk"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="w4xt8u3atk"]{color:#776f62}[data-colorid="kr0lab301e"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="kr0lab301e"]{color:#776f62}[data-colorid="1svqp3asg2"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="1svqp3asg2"]{color:#776f62}[data-colorid="ewcrgephmk"]{color:#9d9588} html[data-color-mode=dark] [data-colorid="ewcrgephmk"]{color:#776f62}</style>
                    </div>

                    
                                                      
                </div>             </div> 
            <div id="footer" role="contentinfo">
                <section class="footer-body">
                    <p>Document generated by Confluence on Okt. 26, 2023 18:02</p>
                    <div id="footer-logo"><a href="http://www.atlassian.com/">Atlassian</a></div>
                </section>
            </div>
        </div>     </body>
</html>
